services:
    mysql:
        image: mysql:9.1.0
        restart: always
        environment:
            MYSQL_DATABASE: symfony_todo_app
            MYSQL_ROOT_PASSWORD: password
        ports:
            -   "3306:3306"
        volumes:
            -   docker-example-symfony-mysql:/var/lib/mysql

    php:
        environment:
            PHP_IDE_CONFIG: "serverName=docker-example-symfony"
        build:
            context: .
            dockerfile: docker/Dockerfile
        ports:
            - "8080:8080"
        volumes:
            - ./:/var/www/html

volumes:
    docker-example-symfony-mysql: