version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - docker-nginx-html-example-network

    nginx:
        image: nginx:mainline-alpine
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/html
            - ./nginx-conf:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - docker-nginx-html-example-network

networks:
    docker-nginx-html-example-network:
        driver: bridge