services:
  app2:
    image: nginx:mainline-alpine
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.app2.entrypoints=web
      - traefik.http.routers.app2.rule=HOST(`app2.localhost`)
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - docker-traefik-example

networks:
  docker-traefik-example:
    external: true
