services:
  app2:
    image: nginx:latest
    container_name: app2-nginx
    labels:
      - traefik.enable=true
      - traefik.http.routers.app2.entrypoints=web
      - traefik.http.routers.app2.rule=HOST(`app2.localhost`)
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    depends_on:
      - php
    networks:
      - docker-traefik-example

  php:
    container_name: app2-php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    networks:
      - docker-traefik-example

  mysql:
    container_name: app2-mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: website
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - docker-traefik-example

volumes:
  mysql-data:

networks:
  docker-traefik-example:
    external: true
