version: '3'

services:
    nginx:
        image: 'nginx:latest'
        depends_on:
            - wordpress
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        networks:
            - sajadtorkamani
    db:
        image: mysql:8.0.32
        volumes:
            - sajadtorkamani-mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress_password
        ports:
            - '3307:3306'
    wordpress:
        depends_on:
            - db
        image: wordpress:latest
        ports:
            - '8000:80'
        volumes:
            - ./wordpress:/var/www/html
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress_password

volumes:
    sajadtorkamani:
    sajadtorkamani-mysql:

networks:
    sajadtorkamani:
        driver: bridge

